# Generated by Django 5.0.3 on 2024-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='lifestyle', unique=True),
            preserve_default=False,
        ),
    ]
